apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fusioniq 
  labels:
    name: backend
    project: fusioniq
    tier: app 
spec:
  replicas: 2
  selector:
    matchLabels: # deployment-set labels
      name: backend
      project: fusioniq
      tier: app
  template: # pod defination
    metadata:
      labels: # pod labels
        name: backend
        project: fusioniq
        tier: app
    spec:
      containers:
      - name: backend
        image: iamroyalreddy/fusion:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fusioniq
spec:
  clusterIP: None
  selector:
    name: backend
    project: fusioniq
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port
