apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-router-config
  namespace: fusioniq
data:
  mysql-router.conf: |
    [DEFAULT]
    logging_folder = /var/log/mysqlrouter
    runtime_folder = /var/run/mysqlrouter
    data_folder = /var/lib/mysqlrouter

    [logger]
    level = INFO

    [metadata_cache:fusioniq]
    bootstrap_server = mysql-master.fusioniq.svc.cluster.local:3306
    user = replica
    metadata_cluster = fusioniq

    [routing:read_write]
    bind_address = 0.0.0.0
    bind_port = 3306
    mode = read-write
    destination = metadata-cache://fusioniq/primary

    [routing:read_only]
    bind_address = 0.0.0.0
    bind_port = 3307
    mode = read-only
    destination = metadata-cache://fusioniq/replicas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-router
  namespace: fusioniq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-router
  template:
    metadata:
      labels:
        app: mysql-router
    spec:
      containers:
        - name: mysql-router
          image: mysql/mysql-router:8.2.0
          command: ["mysqlrouter", "--config", "/etc/mysqlrouter/mysql-router.conf"]
          volumeMounts:
            - name: config
              mountPath: /etc/mysqlrouter
            - name: mysqlrouter-data
              mountPath: /var/lib/mysqlrouter
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: MYSQL_PASSWORD
      volumes:
        - name: config
          configMap:
            name: mysql-router-config
        - name: mysqlrouter-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-router
  namespace: fusioniq
spec:
  ports:
    - name: read-write
      port: 3306
      targetPort: 3306
    - name: read-only
      port: 3307
      targetPort: 3307
  selector:
    app: mysql-router