apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: fusioniq
  labels:
    app: mysql
    project: fusioniq
    tier: db
spec:
  selector:
    matchLabels:
      app: mysql
      project: fusioniq
      tier: db
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        project: fusioniq
        tier: db
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: mysql
        image: iamroyalreddy/mysql:8.0.41
        securityContext:
          runAsUser: 999
        args: []
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 10Gi
--- 
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fusioniq
  labels:
    app: mysql
    project: fusioniq
    tier: db
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306
  selector:
    app: mysql
    project: fusioniq
    tier: db
---