apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: fusioniq 
  labels:
    name: web
    project: fusioniq
    tier: web 
spec:
  replicas: 2
  selector:
    matchLabels: # should match with pod
      name: web
      project: fusioniq
      tier: web
  template: # pod defination
    metadata:
      labels: # pod labels
        name: web
        project: fusioniq
        tier: web
    spec:
      containers:
      - name: web
        image: nginx:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: fusioniq
spec:
  type: LoadBalancer # NodePort
  selector:
    name: web
    project: fusioniq
    tier: web 
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port
