apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fusioniq
  labels:
    app: mysql
    project: fusioniq
    tier: db
spec:
  type: Loadbalancer
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306
  clusterIP: None
  selector:
    app: mysql
    project: fusioniq
    tier: db