apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fusioniq 
  labels:
    name: backend
    project: fusioniq
    tier: app 
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: # deployment-set labels
      name: backend
      project: fusioniq
      tier: app
  template: # pod defination
    metadata:
      labels: # pod labels
        name: backend
        project: fusioniq
        tier: app
    spec:
      containers:
      - name: backend
        image: "iamroyalreddy/fusion:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always